parameters: 
    sorting: true
    followPosture: 
      R: true
      P: true
      Y: true
    grabPosture: 
      DIR_R: 0
      DIR_P: 0
      DIR_Y: 0
    grabOffset: 
      x: 0.0
      y: 0.0
      z: 0.0
    placePosture: 
      DIR_R: 0
      DIR_P: 0
      DIR_Y: 0
    placeOffset: 
      x: 0
      y: 0
      z: 0   
